control:
  port     : 12346
  interface: localhost
socket:
  port     : 12345
  interface: 0.0.0.0
websocket:
  port     : 8080
  interface: 0.0.0.0
http:
  port     : 80
  interface: 0.0.0.0

zigzag:
  host : localhost
  port : 1111
